/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardComponent: typeof import('./src/components/icons/CardComponent.vue')['default']
    RecordModal: typeof import('./src/components/RecordModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwipeCard: typeof import('./src/components/SwipeCard.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
  }
}
